# Generated by Django 5.2.5 on 2026-01-31 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='วันที่')),
                ('total_students', models.IntegerField(default=0, verbose_name='นักเรียนทั้งหมด')),
                ('students_present', models.IntegerField(default=0, verbose_name='มา')),
                ('students_late', models.IntegerField(default=0, verbose_name='มาสาย')),
                ('students_absent', models.IntegerField(default=0, verbose_name='ขาด')),
                ('students_early_leave', models.IntegerField(default=0, verbose_name='ออกก่อนเวลา')),
                ('total_scans', models.IntegerField(default=0, verbose_name='จำนวนการสแกนทั้งหมด')),
                ('successful_scans', models.IntegerField(default=0, verbose_name='สแกนสำเร็จ')),
                ('failed_scans', models.IntegerField(default=0, verbose_name='สแกนล้มเหลว')),
                ('face_recognition_success', models.IntegerField(default=0, verbose_name='ตรวจจับใบหน้าสำเร็จ')),
                ('face_recognition_failed', models.IntegerField(default=0, verbose_name='ตรวจจับใบหน้าล้มเหลว')),
                ('devices_online', models.IntegerField(default=0, verbose_name='อุปกรณ์ออนไลน์')),
                ('devices_offline', models.IntegerField(default=0, verbose_name='อุปกรณ์ออฟไลน์')),
                ('system_alerts_count', models.IntegerField(default=0, verbose_name='จำนวนการแจ้งเตือน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายงานประจำวัน',
                'verbose_name_plural': 'รายงานประจำวัน',
                'db_table': 'daily_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(default='RFID_READER', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('online', 'ออนไลน์'), ('offline', 'ออฟไลน์'), ('maintenance', 'ปิดปรับปรุง'), ('error', 'ขัดข้อง')], default='offline', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('total_scans', models.IntegerField(default=0)),
                ('successful_scans', models.IntegerField(default=0)),
                ('failed_scans', models.IntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_status',
            },
        ),
        migrations.CreateModel(
            name='RFIDScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_card_id', models.CharField(max_length=50, verbose_name='รหัสบัตร RFID')),
                ('scan_type', models.CharField(choices=[('check_in', 'เข้า'), ('check_out', 'ออก'), ('manual', 'บันทึกด้วยตนเอง')], max_length=20, verbose_name='ประเภทการสแกน')),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาสแกน')),
                ('status', models.CharField(choices=[('success', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('pending', 'รอตรวจสอบ')], default='pending', max_length=20, verbose_name='สถานะการสแกน')),
                ('attendance_status', models.CharField(choices=[('present', 'มาปกติ'), ('late', 'มาสาย'), ('absent', 'ขาด'), ('early_leave', 'ออกก่อนเวลา'), ('checkout', 'ออก'), ('no_checkout', 'ไม่สแกนออก'), ('pending', 'รอตรวจสอบ')], default='pending', max_length=20, verbose_name='สถานะการเข้าเรียน')),
                ('points_deducted', models.IntegerField(default=0, verbose_name='คะแนนที่หัก')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='ชื่ออุปกรณ์')),
                ('device_location', models.CharField(blank=True, max_length=200, verbose_name='ตำแหน่งอุปกรณ์')),
                ('device_info', models.TextField(blank=True, verbose_name='ข้อมูลอุปกรณ์')),
                ('error_message', models.TextField(blank=True, verbose_name='ข้อความแสดงข้อผิดพลาด')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='เวลาประมวลผล (วินาที)')),
                ('is_manual', models.BooleanField(default=False, verbose_name='บันทึกด้วยตนเอง')),
                ('manual_notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanning_manual_scan_logs', to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanning_rfid_scan_logs', to='my.student')),
            ],
            options={
                'verbose_name': 'บันทึกการสแกน RFID',
                'db_table': 'rfid_scan_logs',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'ตรวจจับสำเร็จ'), ('failed', 'ตรวจจับล้มเหลว'), ('no_face', 'ไม่พบใบหน้า'), ('multiple_faces', 'พบหลายใบหน้า'), ('mismatch', 'ใบหน้าไม่ตรง'), ('error', 'เกิดข้อผิดพลาด'), ('manual', 'บันทึกด้วยตนเอง')], max_length=20, verbose_name='สถานะ')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='ค่าความมั่นใจ (0-100)')),
                ('captured_image', models.ImageField(blank=True, null=True, upload_to='face_scans/%Y/%m/%d/')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='เวลาประมวลผล (วินาที)')),
                ('face_detection_details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('is_manual', models.BooleanField(default=False, verbose_name='บันทึกด้วยตนเอง')),
                ('manual_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanning_manual_face_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanning_face_recognition_logs', to='my.student')),
                ('rfid_scan_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_logs', to='scanning.rfidscanlog')),
            ],
            options={
                'verbose_name': 'บันทึกการตรวจจับใบหน้า',
                'db_table': 'face_recognition_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('device_offline', 'อุปกรณ์ออฟไลน์'), ('face_recognition_failed', 'ตรวจจับใบหน้าล้มเหลว'), ('unauthorized_access', 'พยายามเข้าถึงโดยไม่ได้รับอนุญาต'), ('system_error', 'ข้อผิดพลาดของระบบ'), ('maintenance', 'แจ้งเตือนบำรุงรักษา'), ('other', 'อื่นๆ')], max_length=50, verbose_name='ประเภท')),
                ('severity', models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง'), ('critical', 'วิกฤต')], default='medium', max_length=20, verbose_name='ระดับความรุนแรง')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='แก้ไขแล้ว')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='แก้ไขเมื่อ')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='หมายเหตุการแก้ไข')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanning.devicestatus', verbose_name='อุปกรณ์')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanning_resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='แก้ไขโดย')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanning_system_alerts', to='my.student', verbose_name='นักเรียน')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือนระบบ',
                'verbose_name_plural': 'การแจ้งเตือนระบบ',
                'db_table': 'system_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rfidscanlog',
            index=models.Index(fields=['rfid_card_id', 'scan_time'], name='rfid_scan_l_rfid_ca_9b1fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidscanlog',
            index=models.Index(fields=['student', 'scan_time'], name='rfid_scan_l_student_4b816f_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidscanlog',
            index=models.Index(fields=['scan_type', 'status'], name='rfid_scan_l_scan_ty_6130d4_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidscanlog',
            index=models.Index(fields=['attendance_status', 'scan_time'], name='rfid_scan_l_attenda_7336ff_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['is_resolved', 'created_at'], name='system_aler_is_reso_ab0cff_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['severity', 'is_resolved'], name='system_aler_severit_78434c_idx'),
        ),
    ]
